### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by Yuhang-CADD** [Yuhang-CADD/test#3]
**Date**: Nov 8th 2022
**Time**: 2pm UK time ([[other times](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=11&day=8&hour=14&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240)](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=11&day=8&hour=14&min=0&sec=0&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))

**Place**: [https://ucl.zoom.us/j/91379419977](https://ucl.zoom.us/j/91379419977)

**Recording**:

**Previous Meeting**: #90
**Who can come?**: Anyone. No need to say anything unless you'd like to.

*Apologies*: @mattodd
*Decks*: Please @opensourceantibiotics/murligase remember that if you share slides/info, to drag and drop those into a comment on this page, below. *Very easy and saves @mattodd having to pester you.*

**Agenda**:

Key things today are
i) Follow-up screening of multi-targeting compounds from Warwick and Atomwise collections
ii) Do we need Soak-In Follow Up (this was mentioned in the original #80) action on @mattodd
*(please add if you'd like to prioritise anything)*

### 1) Multi-targeting Compounds from the Warwick/NEU Enamine Collection

- [ ]  @AJLloyd105 @chrisdowson1 to update on further enzymatic screening of the Warwick Enamine Collection, following discovery of the hits shown [[here](https://github.com/opensourceantibiotics/murligase/issues/86#issuecomment-1181679561)](https://github.com/opensourceantibiotics/murligase/issues/86#issuecomment-1181679561).
- [ ]  Additional near-neighbour compounds have been ordered by @edwintse #89, @edwintse to update.
- [ ]  @LauraDS1 to update on any soaking and/or co-crystallisation experiments with these compounds (last update [[here](https://github.com/opensourceantibiotics/murligase/issues/87#issuecomment-1209897588)](https://github.com/opensourceantibiotics/murligase/issues/87#issuecomment-1209897588)). Last time @LauraDS1 reported that the analysis of the Enamine compounds by SPR was underway (hits have been found!) @LauraDS1 to update. Crucial Q: is there correlation between hits observed by SPR and hits observed by enzymatic screening? See also below for comments on the use of an alternative assay for the Atomwise compounds.

### 2) Multi-targeting Elaborated Fragments from Diamond Fragment Screen

- [ ]  @LauraDS1 to update on screening (inhibition, SPR, soak) of elaborated fragments sent by @edwintse in #84.

### 3) Atomwise Hits

- [ ]  @LauraDS1 is waiting for a new sensor type to redo SPR experiments (MurC, MurD in presence and absence of ADP/AMPPNP) on Atomwise compounds (#55 and on [[wiki](https://github.com/opensourceantibiotics/murligase/wiki/SPR-with-the-Atomwise-library)](https://github.com/opensourceantibiotics/murligase/wiki/SPR-with-the-Atomwise-library)), following the [[previous crystal structures of several compounds bound](https://github.com/opensourceantibiotics/murligase/wiki/XChem-EcMurE-Atomwise-library-1)](https://github.com/opensourceantibiotics/murligase/wiki/XChem-EcMurE-Atomwise-library-1) (see also #52). To Do: these data need to be cross-checked with the new inhibition data presented by @AJLloyd105 ([[slides](https://github.com/opensourceantibiotics/murligase/blob/master/Talks_Meetings_Events/2022%20Sept%20Meeting/Adrian%20Lloyd%20et%20al%20130922%20IV.pptx)](https://github.com/opensourceantibiotics/murligase/blob/master/Talks_Meetings_Events/2022%20Sept%20Meeting/Adrian%20Lloyd%20et%20al%20130922%20IV.pptx)) to see if we have any X-ray structures of these inhibitors. **In meeting**: In the initial screen by @AJLloyd105, 15 of the compounds interfered with the coupling enzymes. 14 of those also interfered with an alternative assay (which is?), but one did not, and has been added to the list of compounds found to be inhibitors in the Atomwise set.
- [ ]  Residual item to do: @LauraDS1 @LizbeK to clarify, on the [[wiki here](https://github.com/opensourceantibiotics/murligase/wiki/XChem-EcMurE-Atomwise-library-1)](https://github.com/opensourceantibiotics/murligase/wiki/XChem-EcMurE-Atomwise-library-1), whether the Atomwise compounds that have been co-crystallised have a binding site that overlaps with the [["target site" Atomwise used](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1032524627)](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1032524627) @LauraDS1 addressed this [[here](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1032639180)](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1032639180) and in the March meeting there was discussion that the Atomwise compounds **did** bind in a partial overlap with the intended binding site. This has been clarified as part of #69, and *all we need now is @LauraDS1 to summarise briefly on wiki what we know*.
- [ ]  Based on the above, and the near neighbours identified by @edwintse, @mattodd to follow up with Denzil Bernard about potential additional suggestions from Atomwise. Note that we're being asked for this: "I have attached your data reporting form that will help us interpret your results. The form is organized by plate location and tube barcode, so please check to ensure that the tube barcode matches the reported results. Feel free to modify the form to fit your experiment" where the relevant spreadsheet is [[here](https://github.com/opensourceantibiotics/murligase/tree/master/Atomwise/Data%20Back%20to%20Atomwise)](https://github.com/opensourceantibiotics/murligase/tree/master/Atomwise/Data%20Back%20to%20Atomwise), screenshot below.

![https://user-images.githubusercontent.com/4386101/189902447-f57ddf96-fa8e-49cc-bdc5-ba569132b0ee.png](https://user-images.githubusercontent.com/4386101/189902447-f57ddf96-fa8e-49cc-bdc5-ba569132b0ee.png)

### 4) Variants of AZ Compounds

- [x]  @Yuhang-CADD to update on the shipping of AZ5595 and the amino derivative of that compound (OSA_001095). **In meeting**: @Yuhang-CADD's amine compound is likely to be the formate salt, which should be factored into the molecular weight calculation. @Yuhang-CADD to confirm with @LauraDS1.
- [ ]  @Yuhang-CADD to consider which proteins we should ask SSGCID to crystallise with these compounds, activity is found at Warwick @LauraDS1 the results were shown [[here](https://github.com/opensourceantibiotics/murligase/wiki/SPR-evaluation-of-WYH-compounds)](https://github.com/opensourceantibiotics/murligase/wiki/SPR-evaluation-of-WYH-compounds) - Need to be further validated by enzymatic assays?
- [ ]  @Yuhang-CADD to report on progress towards making other analogues of pyrazolopyrimidine inhibitors.
- [ ]  @mattodd to reach out to groups that may be happy to run accumulation assays, both on the AZ amine and more generally on new compounds made e.g. Hergenrother lab (e.g. student Rebecca Ulrich), Helen Zgurskaya (Oklahoma).
- [ ]  @Rebecca-Steventon to report on the assay @Yuhang-CADD 's compound (*which?*) [[here](https://github.com/opensourceantibiotics/murligase/issues/54#issuecomment-964167068)](https://github.com/opensourceantibiotics/murligase/issues/54#issuecomment-964167068).
- [ ]  @chrisdowson1 to work on compound transfer from SSGCID to Warwick and update the group. *Does this need an update, or can it be mothballed?*

### 5) New Protein Structures

Last time we updated [[the PDB list](https://github.com/opensourceantibiotics/murligase/wiki/PDB-and-Fragalysis)](https://github.com/opensourceantibiotics/murligase/wiki/PDB-and-Fragalysis) with new structures: 8EGM, 8EGN, 8DOF, 8DP2 (this one needs collating together with other structures in [[wiki page](https://github.com/opensourceantibiotics/murligase/wiki/PDB-and-Fragalysis)](https://github.com/opensourceantibiotics/murligase/wiki/PDB-and-Fragalysis) or #67). 

(More details https://github.com/opensourceantibiotics/murligase/issues/90)

Waiting for Jan Abendroth to update the final SSGCID X-ray collection for MurC with compound AZ-13644923 (AZcmpd 26) during our APS shift. 

![https://user-images.githubusercontent.com/58538740/195100038-1bc8cd08-7f79-4c90-9025-e3ea014347f4.png](https://user-images.githubusercontent.com/58538740/195100038-1bc8cd08-7f79-4c90-9025-e3ea014347f4.png)

Thank you Jan!

A discussion of the possible value of truncated structures was had as part of the Soak-In at #80. <-- any conclusions we can summarise? New Soak-in meeting will be organised by @mattodd

### 6) De Novo Computational Modelling

- [ ]  @edwintse @danielgedder to complete synthesis of molecules suggested in #85. (All the Enamine compounds have now been purchased by @edwintse and will be shipped to Warwick in ~ 4 weeks.)
- [ ]  @LauraDS1 to book an SPR screen in the last week in August (week of 29th?). **In meeting**: @LauraDS1 updated on the analysis of the competition compounds (#85) by SPR. Data summarised [[here](https://github.com/opensourceantibiotics/murligase/wiki/Generative-Modelling-Competition%3A-SPR-results)](https://github.com/opensourceantibiotics/murligase/wiki/Generative-Modelling-Competition%3A-SPR-results). The data are complete (repeats already done). There are some hits at 100 uM, *and one at about 10 uM*, which is exciting. Some compounds gave non-specific binding (straight line SPR curve). Obviously no info on *where* the compounds are binding.
- [ ]  @LauraDS1 to evaluate the competition compounds in a crystal soaking assay.
@AJLloyd105 reported that the competition compounds had been screened *vs.* Pae MurD enzymatically. High levels of inhibition were observed, but the compounds all also interfered with the coupling enzymes used in the assay, unfortunately. Solutions: 1) reduce the concentration of the test compounds to find a window where the assay works, or 2) find a different assay.
- [ ]  @Yuhang-CADD to report on progress towards @jhjensen2's originally-suggested compounds (last update was [[here](https://github.com/opensourceantibiotics/murligase/issues/75#issuecomment-1122296547)](https://github.com/opensourceantibiotics/murligase/issues/75#issuecomment-1122296547))

### 7) Other Potential Starting Points

- [ ]  @chrisdowson1 to summarise status of LifeArc projects, both the previous collaboration and the more recent fragment screening campaigns (with Peter Coombs). Data for the latter has been transferred to Warwick. @mattodd to clarify that all parties are happy for the data to be released into the public domain. @mattodd awaiting reply.
- [ ]  Assuming above OK, update to be presented by someone from the Warwick team on enzymatic testing of the LifeArc fragments (which were discovered via an SPR screen). No structural information yet.
- [ ]  @chrisdowson1 to report on progress towards securing the [[Merck Open Global Health Library](https://www.merckgroup.com/en/research/open-innovation/biopharma-open-innovation-portal/open-global-health-library.html)](https://www.merckgroup.com/en/research/open-innovation/biopharma-open-innovation-portal/open-global-health-library.html).

### 8) Misc/AOB

**In meeting**: @AJLloyd105  reported on the evaluation, enzymatically, of "double-headed" compounds containing uridine and ATP binders: . These were found to be binders and will be investigated further (*need to upload deck*).

- [ ]  @mattodd to post GRC conference slides somewhere (28 MB...).
- [ ]  We need a volunteer to reach out to [[CC4CARB](https://www.cc4carb-collection.org/)](https://www.cc4carb-collection.org/) to assess whether we are suitable for a proposal.

### 9) List of any Raw Data That Needs Posting Online

Suitable locations: ideally an electronic lab notebook, another suitable repository (Zenodo, Figshare) or Github itself.

- [ ]  @Rebecca-Steventon - dose-response data for potential dual inhibitors OSA742, OSA754, OSA759, OSA789 that was summarised in [[this graphic](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1073554468)](https://github.com/opensourceantibiotics/murligase/issues/66#issuecomment-1073554468).

### 9) Mothballs (if no actions then these need to be linked in wiki and closed)

- [ ]  @Rebecca-Steventon has posted data of @LizbeK fragment screen ([https://github.com/opensourceantibiotics/murligase/wiki/Pocket-binding-site](https://github.com/opensourceantibiotics/murligase/wiki/Pocket-binding-site) - but @drc007 would like structures to be added).
- [ ]  @LauraDS1 to liaise with Peter and @LizbeK to see if a soak of the @eyermanncj Enamine compounds is possible at Diamond.
- [ ]  Comparative analysis was done by @ZigBu of mur ligase ATP binding sites (#56). Any learnings?
- [ ]  @ZigBu also posted (#57) on a [[paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0152075)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0152075) highlighting that mur domain movement may not be dependent on substrate binding. Again, anything we need to consider? @eyermanncj posted "As a reminder the dynamics of E. coli murD is well established. [[Here](https://dx.doi.org/10.1038/srep16685)](https://dx.doi.org/10.1038/srep16685) is a “recent” NMR study on E. coli murD."
- [ ]  @mattodd @chrisdowson1 have parked the idea of a Euro Lead Factory screen.
- [ ]  Do we need to consider the importance of the observed carbamoylation of a residue (Lys198 (-> KCX198) in a structure (7TI7). Does this influence inhibitor design? See @eyermanncj's [[analysis](https://github.com/opensourceantibiotics/murligase/issues/67#issuecomment-1054777581)](https://github.com/opensourceantibiotics/murligase/issues/67#issuecomment-1054777581)
- [ ]  @eyermanncj and @chrisdowson1 to speak to the benefits of ordering the Enamine kinase library. *Should this be mothballed?*

### Next Meeting

Dec 6th 2pm UK time.

### L'esprit de l'escalier

If you'd like to follow up after the meeting, please comment below. You can also email, but please be clear if anything in the email should not be public domain - the default is always open.

**Comment by Yuhang-CADD** [comment]
<img width="1440" alt="Screenshot 2023-10-12 at 15 15 04" src="https://github.com/Yuhang-CADD/test/assets/58538740/56314202-5d86-43c1-9ae8-ad5cf5032d6a">
